model = "gpt-oss:20b"
model_provider = "gpt-oss-responses"
model_context_window = 96000
max_output_tokens = 32000
approval_policy = "never"
sandbox_mode = "danger-full-access"
disable_response_storage = false
model_supports_reasoning_summaries = true
tools_web_search_request = true

[model_providers.gpt-oss-responses]
name = "gpt-oss-responses"
base_url = "http://host.docker.internal/v1"
wire_api = "responses"
request_max_retries = 4
stream_max_retries = 10
stream_idle_timeout_ms = 300000
