{
 "title": "ZFS Details",
 "description": "ZFS monitoring dashboard for Unraid",
 "tags": [
  "zfs",
  "nas"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "query": "30s" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(zfs_pool_allocated_bytes{job=\"$job\"},pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZFS Pool Detail",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_dataset_used_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_health{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_fragmentation_ratio{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_free_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_dataset_referenced_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_pool_size_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_dataset_written_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Growth by Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(zfs_pool_allocated_bytes{job=\"$job\", pool=~\"$pool\"}[1d])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_pool_allocated_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "{{name}} - Used"
    },
    {
     "expr": "zfs_pool_size_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "{{name}} - Size"
    },
    {
     "expr": "zfs_pool_free_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "{{name}} - Free"
    }
   ]
  },
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "ARC Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{job=\"$job\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{job=\"$job\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "node_zfs_arc_mfu_size{job=\"$job\"}",
     "legendFormat": "Most Frequently Used"
    },
    {
     "expr": "node_zfs_arc_dnode_size{job=\"$job\"}",
     "legendFormat": "Dnode Size"
    },
    {
     "expr": "node_zfs_arc_mru_size{job=\"$job\"}",
     "legendFormat": "Most Recently Used"
    },
    {
     "expr": "node_zfs_arc_size{job=\"$job\"}",
     "legendFormat": "ARC Size"
    }
   ]
  },
  {
   "title": "ARC Demand - Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{job=\"$job\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_misses{job=\"$job\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{job=\"$job\"}[5m]) / (rate(node_zfs_arc_demand_data_misses{job=\"$job\"}[5m]) + (rate(node_zfs_arc_demand_data_hits{job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "ARC Demand - Metadata",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{job=\"$job\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_misses{job=\"$job\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{job=\"$job\"}[5m]) / (rate(node_zfs_arc_demand_metadata_misses{job=\"$job\"}[5m]) + (rate(node_zfs_arc_demand_metadata_hits{job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  { "title": "Pool Stats - $pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 }, "repeat": "pool" },
  {
   "title": "Pool Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_pool_allocated_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "zfs_pool_size_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "zfs_pool_free_bytes{job=\"$job\", pool=~\"$pool\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Pool Reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(zfs_dataset_referenced_bytes{job=\"$job\", pool=\"$pool\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(node_zfs_zpool_dataset_reads{job=\"nas_metrics\", zpool=\"$pool\"}[5m])",
     "legendFormat": "{{dataset}} IOPS"
    }
   ]
  },
  {
   "title": "Pool Writes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(zfs_dataset_written_bytes{job=\"$job\", pool=\"$pool\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(node_zfs_zpool_dataset_writes{job=\"$job\", zpool=\"$pool\"}[5m])",
     "legendFormat": "{{dataset}} IOPS"
    }
   ]
  }
 ]
}