name: Cache 📝

on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "**.age"
      - "flake.lock"

concurrency:
  group: ci-${{ github.ref }}-cache
  cancel-in-progress: true

jobs:
  cache:
    name: Cache 📝
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04-arm
            derivation: ".#nixosConfigurations.bpi.config.system.build.toplevel"
    runs-on: ${{ matrix.image }}
    environment: production
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: dlubawy
          extraPullNames: nix-community
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build derivation
        run: nix build ${{ matrix.derivation }}
