name: check-flake

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13
      - name: Run check
        run: make check
  merge:
    if: ${{ github.event.pull_request.user.login == 'dlubawy-bot[bot]' }}
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - run: |
          curl -L \
           -X PUT \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number}}/merge \
           -d '{"commit_title":"${{github.event.pull_request.title}}","sha":"${{github.event.pull_request.head.sha}}","merge_method":"squash"}'
