name: Format 🔎

on:
  push:

concurrency:
  group: ci-${{ github.ref }}-format
  cancel-in-progress: true

jobs:
  format:
    name: Format 🔎
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa
      - name: Running prek 🚧
        run: "nix develop --command prek run --all-files"
