name: Format 🔎

on:
  push:

concurrency:
  group: ci-${{ github.ref }}-format
  cancel-in-progress: true

jobs:
  format:
    name: Format 🔎
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
      - name: Running prek 🚧
        run: "nix develop --command prek run --all-files"
