name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    outputs:
      os: ${{ steps.changes.outputs.changes }}
      nix-changes: ${{ steps.changes.outputs['macos-15'] == 'true' || steps.changes.outputs['ubuntu-latest'] == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: changes
        with:
          filters: |
            macos-15:
              - "flake.lock"
              - "flake.nix"
              - "modules/{home-manager,nix-configs,nixvim,topology}/**.nix"
              - "overlays/**.nix"
              - "pkgs/**.nix"
              - "users/**.nix"
              - "**.age"
              - "hosts/laplace/**.nix"
              - "modules/darwin/**.nix"
            ubuntu-latest:
              - "flake.lock"
              - "flake.nix"
              - "modules/{home-manager,nix-configs,nixvim,topology}/**.nix"
              - "overlays/**.nix"
              - "pkgs/**.nix"
              - "users/**.nix"
              - "**.age"
              - "homes/**.nix"
              - "hosts/{bpi,kepler,lil-nas,syringa}/**.nix"
              - "modules/nixos/**.nix"
  check:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.nix-changes == 'true' }}
    strategy:
      matrix:
        os: ${{ fromJSON(needs.detect-changes.outputs.os) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: dlubawy
          extraPullNames: nix-community
      - name: Run flake check
        run: nix develop --command just check
  check-results:
    needs:
      - check
      - detect-changes
    if: ${{ always() && contains(needs.detect-changes.result, 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine check results
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "One or more checks failed" 1>&2
            exit 1
          elif [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more checks cancelled" 1>&2
            exit 1
          else
            echo "All checks completed successfully or were skipped"
            exit 0
          fi
  merge:
    if: ${{ github.event.pull_request.user.login == 'dlubawy-bot[bot]' && github.repository == 'dlubawy/nix-configs' }}
    needs: check-results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
      - name: Merge pull request
        run: |
          curl -L \
           -X PUT \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number}}/merge \
           -d '{"commit_title":"${{github.event.pull_request.title}}","sha":"${{github.event.pull_request.head.sha}}","merge_method":"squash"}'
